# -*- coding: utf-8 -*-
"""gradio_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/oshikatiwari/Semantic-Book-Recommender/blob/main/gradio_dashboard.ipynb
"""



import pandas as pd
import numpy as np
import gradio as gr

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

books = pd.read_csv("books_with_emotions.csv")

books.head()

books["large_thumbnail"] = books["thumbnail"].fillna(
    "https://via.placeholder.com/128x200?text=No+Cover"
)

books["large_thumbnail"] = books["large_thumbnail"].str.replace(
    "http://",
    "https://"
) + "&fife=w800"

raw_documents = TextLoader(
    "tagged_description.txt"
).load()

text_splitter = CharacterTextSplitter(
    chunk_size=1,
    chunk_overlap=0,
    separator="\n"
)

documents = text_splitter.split_documents(raw_documents)

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db_books = Chroma.from_documents(
    documents=documents,
    embedding=embeddings
)

def retrieve_semantic_recommendations(
    query: str,
    category: str = "All",
    tone: str = "All",
    initial_top_k: int = 50,
    final_top_k: int = 16,
) -> pd.DataFrame:

    recs = db_books.similarity_search_with_score(
        query,
        k=initial_top_k
    )

    books_list = [
        int(rec[0].page_content.strip('"').split()[0])
        for rec in recs
    ]

    book_recs = books[books["isbn13"].isin(books_list)].drop_duplicates(
        subset=["isbn13"]
    )

    if category != "All":
        book_recs = book_recs[
            book_recs["simple_categories"] == category
        ]

    if tone == "Happy":
        book_recs = book_recs.sort_values(
            by="joy_x",
            ascending=False
        )

    elif tone == "Surprising":
        book_recs = book_recs.sort_values(
            by="surprise_x",
            ascending=False
        )

    elif tone == "Angry":
        book_recs = book_recs.sort_values(
            by="anger_x",
            ascending=False
        )

    elif tone == "Suspenseful":
        book_recs = book_recs.sort_values(
            by="fear_x",
            ascending=False
        )

    elif tone == "Sad":
        book_recs = book_recs.sort_values(
            by="sadness_x",
            ascending=False
        )

    return book_recs.head(final_top_k)

def recommend_books(
    query: str,
    category: str,
    tone: str,
):
    recommendations = retrieve_semantic_recommendations(
        query,
        category,
        tone
    )

    results = []

    for _, row in recommendations.iterrows():

        description = row["description"]
        truncated_description = " ".join(
            description.split()[:30]
        ) + "..."

        authors_split = row["authors"].split(";")

        if len(authors_split) == 2:
            authors_str = f"{authors_split[0]} and {authors_split[1]}"
        elif len(authors_split) > 2:
            authors_str = f"{','.join(authors_split[:-1])}, and {authors_split[-1]}"
        else:
            authors_str = row["authors"]

        caption = (
            f"{row['title']} by {authors_str}: "
            f"{truncated_description}"
        )

        results.append(
            (row["large_thumbnail"], caption)
        )

    return results

categories = ["All"] + sorted(books["simple_categories"].dropna().unique())

tones = [
    "All",
    "Happy",
    "Surprising",
    "Angry",
    "Suspenseful",
    "Sad"
]


with gr.Blocks(theme=gr.themes.Glass()) as dashboard:

    gr.Markdown("# Semantic Book Recommender")

    with gr.Row():

        user_query = gr.Textbox(
            label="Please enter a description of a book:",
            placeholder="e.g., A story about forgiveness"
        )

        category_dropdown = gr.Dropdown(
            choices=categories,
            label="Select a category:",
            value="All"
        )

        tone_dropdown = gr.Dropdown(
            choices=tones,
            label="Select an emotional tone:",
            value="All"
        )

        submit_button = gr.Button(
            "Find recommendations"
        )


    gr.Markdown("## Recommendations")

    output = gr.Gallery(
        label="Recommended books",
        columns=8,
        rows=2
    )


    submit_button.click(
        fn=recommend_books,
        inputs=[
            user_query,
            category_dropdown,
            tone_dropdown
        ],
        outputs=output
    )


dashboard.launch(
    server_name="0.0.0.0",
    server_port=7860
)

